version: '3'


services:
  inventory-service:
    image: inventory-service:latest
    build:
      context: .
      dockerfile: ./inventory/Dockerfile
    container_name: inventory-service-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:./data/inventory_service_db
      - SPRING_DATASOURCE_USERNAME=inventory_service_user
      - SPRING_DATASOURCE_PASSWORD=inventory_service_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - OTEL_RESOURCE_ATTRIBUTES=service.name=inventory-service
      - OTEL_PROPAGATORS=b3
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8009:8009"
    networks:
      - my-network
  rating-review-service:
    image: rating-review-service:latest
    build:
      context: .
      dockerfile: ./rating_review_service/Dockerfile
    container_name: rating-review-service-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:./data/rating_review_service_db
      - SPRING_DATASOURCE_USERNAME=rating_review_service_user
      - SPRING_DATASOURCE_PASSWORD=rating_review_service_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rating-review-service
      - OTEL_PROPAGATORS=b3
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8002:8002"
    networks:
      - my-network
    
  user-service:
    image: user-service:latest
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    container_name: user-service-cointainer
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=user-service
    ports:
      - "8005:8005"
    networks:
      - my-network
    

  api-gateway:
    image: api-gateway:latest
    build:
      context: .
      dockerfile: ./OtelApiGateway/Dockerfile
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=api-gateway
    ports:
      - "8006:8006"
    networks:
      - my-network
    
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - my-network
    ports:
      - "16686:16686"
      - "14250"
    
  
  zipkin:
    image: openzipkin/zipkin-slim:latest
    networks:
      - my-network
    ports:
      - "9412:9411"
    
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    networks:
      - my-network
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "55680:55680"
      - "9411:9411"
    depends_on:
      - jaeger
      - zipkin

  
networks:
  my-network: 
    driver: bridge